project:
  title: "Heterogeneity & uncertainty"
  render:
    - index.qmd
  output-dir: docs

site-url: https://mvuorre.github.io/heterogeneity-uncertainty
repo-url: https://github.com/mvuorre/heterogeneity-uncertainty
archive-url: https://doi.org/10.5281/zenodo.19070789
preprint-url: https://osf.io/preprints/psyarxiv/mwg4f

execute:
  freeze: auto
